# Default application configuration that all configurations inherit from.
# Documentation: https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
exclude: 'scss/vendors/*'
exclude: 'scss/app.scss'

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorVariable:
    enabled: false

  PropertySortOrder:
    order: concentric
